use_frameworks!

pod 'CGLayout', :path => '../'

  target 'CGLayout_Example' do

    target 'CGLayout_Tests' do
      inherit! :search_paths

    end
  end
  target 'CGLayout-tvOS' do
  end
  target 'CGLayout-macOS' do
      target 'CGLayout-macOSTests' do
          inherit! :search_paths
      end
  end
