output: docs
swift_version: 4.2
exclude: Sources/Classes/evolution.cglayout/*
xcodebuild_arguments:
    - "-project"
    - "CGLayout.xcodeproj"
    - "-scheme"
    - "CGLayout-Package"

theme: apple
author: Koryttsev Denis
